# Generated by Django 4.1.7 on 2023-03-13 22:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True, verbose_name='URL')),
                ('short_descrtiprion', models.CharField(max_length=512, verbose_name='Короткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('image', models.ImageField(blank=True, upload_to='post_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'gif', 'webp'))], verbose_name='Превью')),
                ('status', models.PositiveSmallIntegerField(choices=[('PUBLISHED', 'Черновик'), ('DRAFT', 'Опубликовано')], default=0, verbose_name='Статус поста')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('fixed', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_posts', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('-fixed', '-created'),
            },
        ),
        migrations.AddIndex(
            model_name='blogposts',
            index=models.Index(fields=['-fixed', '-created', 'status'], name='blog_blogpo_fixed_d751e6_idx'),
        ),
    ]
