# Generated by Django 4.1.7 on 2023-03-21 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="image",
            field=models.ImageField(
                upload_to="post_images/%y/%m/%d",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("png", "jpg", "jpeg", "gif", "webp")
                    )
                ],
                verbose_name="Превью",
            ),
        ),
    ]
