# Generated by Django 4.1.7 on 2023-03-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_categories_description_alter_categories_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='short_descrtiprion',
            new_name='short_description',
        ),
    ]
