# Generated by Django 4.1.7 on 2023-03-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_posts_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="slug",
            field=models.SlugField(blank=True, max_length=32, verbose_name="URL"),
        ),
    ]
