# Generated by Django 4.1.7 on 2023-03-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_short_descrtiprion_posts_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
        ),
    ]
