# Generated by Django 4.1.7 on 2023-04-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_profilecomments_user"),
        ("blog", "0006_comments_comments_blog_commen_created_cac906_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="post_views", to="users.ip"
            ),
        ),
    ]
