# Generated by Django 4.1.7 on 2023-03-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_posts_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-created',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='short_description',
            field=models.CharField(blank=True, max_length=128, verbose_name='Короткое описание'),
        ),
    ]
