# Generated by Django 4.1.7 on 2023-04-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_subscription"),
        ("blog", "0007_posts_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="views",
            field=models.ManyToManyField(
                blank=True, default=0, related_name="views", to="users.ip"
            ),
        ),
    ]
