# Generated by Django 4.1.7 on 2023-03-16 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="https://ui-avatars.com/api/?size=150&background=random&name=<django.db.models.fields.SlugField>",
                upload_to="users_images/%y/%m/%d",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("png", "jpg", "jpeg", "gif", "webp")
                    )
                ],
                verbose_name="Аватар",
            ),
        ),
    ]
