# Generated by Django 4.1.7 on 2023-03-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="is_valid",
            field=models.BooleanField(default=True),
        ),
    ]
