# Generated by Django 4.1.7 on 2023-03-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ip",
            name="user",
            field=models.CharField(default="Anonymous", max_length=150),
        ),
    ]
