# Generated by Django 4.1.7 on 2023-04-02 13:24

from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_ip_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ip",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ip",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
