# Generated by Django 4.1.7 on 2023-04-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ИД пользователя в телеграме'),
        ),
    ]
